// Code generated by https://github.com/go-dev-frame/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/go-dev-frame/sponge/pkg/logger"
	//"github.com/go-dev-frame/sponge/pkg/middleware"

	schoolV1 "school/api/school/v1"
	"school/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		teacherMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			teacherRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewTeacherHandler())
		})
}

func teacherRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService schoolV1.TeacherLogicer) {
	schoolV1.RegisterTeacherRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		schoolV1.WithTeacherLogger(logger.Get()),
		schoolV1.WithTeacherHTTPResponse(),
		schoolV1.WithTeacherErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func teacherMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/teacher/:id  will take effect
	// c.setGroupPath("/api/v1/teacher", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/teacher", middleware.Auth())    // Create teacher
	//c.setSinglePath("DELETE", "/api/v1/teacher/:id", middleware.Auth())    // DeleteByID delete teacher by id
	//c.setSinglePath("PUT", "/api/v1/teacher/:id", middleware.Auth())    // UpdateByID update teacher by id
	//c.setSinglePath("GET", "/api/v1/teacher/:id", middleware.Auth())    // GetByID get teacher by id
	//c.setSinglePath("POST", "/api/v1/teacher/list", middleware.Auth())    // List of teacher by query parameters
	//c.setSinglePath("POST", "/api/v1/teacher/delete/ids", middleware.Auth())    // DeleteByIDs delete teacher by batch id
	//c.setSinglePath("POST", "/api/v1/teacher/condition", middleware.Auth())    // GetByCondition get teacher by condition
	//c.setSinglePath("POST", "/api/v1/teacher/list/ids", middleware.Auth())    // ListByIDs list of teacher by batch id
	//c.setSinglePath("GET", "/api/v1/teacher/list", middleware.Auth())    // ListByLastID list teacher by last id
}
