// Code generated by https://github.com/go-dev-frame/sponge

package handler

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
	"net/http"
	"school/internal/ecode"

	//"github.com/go-dev-frame/sponge/pkg/gin/middleware"

	schoolV1 "school/api/school/v1"
)

var _ schoolV1.FileLogicer = (*fileHandler)(nil)

type fileHandler struct {
}

// NewFileHandler create a handler
func NewFileHandler() schoolV1.FileLogicer {
	return &fileHandler{}
}

// CreateFile ......
func (h *fileHandler) CreateFile(ctx context.Context, req *schoolV1.UploadFileRequest) (*schoolV1.UploadFileResponse, error) {
	c, _ := middleware.AdaptCtx(ctx)
	c.JSON(http.StatusOK, gin.H{"status": "Files uploaded successfully"})
	return nil, ecode.SkipResponse
}
