// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// user business-level http error codes.
// the userNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	userNO       = 8
	userName     = "user"
	userBaseCode = errcode.HCode(userNO)

	ErrLoginUser = errcode.NewError(userBaseCode+1, "failed to Login "+userName)
	ErrHelloUser = errcode.NewError(userBaseCode+2, "failed to Hello "+userName)

	// error codes are globally unique, adding 1 to the previous error code
)
