// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
)

type FileLogicer interface {
	CreateFile(ctx context.Context, req *UploadFileRequest) (*UploadFileResponse, error)
}

type FileOption func(*fileOptions)

type fileOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *fileOptions) apply(opts ...FileOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithFileHTTPResponse() FileOption {
	return func(o *fileOptions) {
		o.isFromRPC = false
	}
}

func WithFileRPCResponse() FileOption {
	return func(o *fileOptions) {
		o.isFromRPC = true
	}
}

func WithFileResponser(responser errcode.Responser) FileOption {
	return func(o *fileOptions) {
		o.responser = responser
	}
}

func WithFileLogger(zapLog *zap.Logger) FileOption {
	return func(o *fileOptions) {
		o.zapLog = zapLog
	}
}

func WithFileErrorToHTTPCode(e ...*errcode.Error) FileOption {
	return func(o *fileOptions) {
		o.httpErrors = e
	}
}

func WithFileRPCStatusToHTTPCode(s ...*errcode.RPCStatus) FileOption {
	return func(o *fileOptions) {
		o.rpcStatus = s
	}
}

func WithFileWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) FileOption {
	return func(o *fileOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterFileRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic FileLogicer,
	opts ...FileOption) {

	o := &fileOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &fileRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type fileRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                FileLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *fileRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/files", r.withMiddleware("POST", "/api/v1/files", r.CreateFile_0)...)

}

func (r *fileRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *fileRouter) CreateFile_0(c *gin.Context) {
	req := &UploadFileRequest{}

	var ctx context.Context = c

	out, err := r.iLogic.CreateFile(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
