// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type UserLogicer interface {
	Create(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error)
	DeleteByID(ctx context.Context, req *DeleteUserByIDRequest) (*DeleteUserByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateUserByIDRequest) (*UpdateUserByIDReply, error)
	GetByID(ctx context.Context, req *GetUserByIDRequest) (*GetUserByIDReply, error)
	List(ctx context.Context, req *ListUserRequest) (*ListUserReply, error)
	DeleteByIDs(ctx context.Context, req *DeleteUserByIDsRequest) (*DeleteUserByIDsReply, error)
	GetByCondition(ctx context.Context, req *GetUserByConditionRequest) (*GetUserByConditionReply, error)
	ListByIDs(ctx context.Context, req *ListUserByIDsRequest) (*ListUserByIDsReply, error)
	ListByLastID(ctx context.Context, req *ListUserByLastIDRequest) (*ListUserByLastIDReply, error)
	Login(ctx context.Context, req *LoginRequest) (*LoginResult, error)
	Info(ctx context.Context, req *LoginRequest) (*LoginResult, error)
	Codes(ctx context.Context, req *LoginRequest) (*LoginResult, error)
	Logout(ctx context.Context, req *LoginRequest) (*LoginResult, error)
}

type UserOption func(*userOptions)

type userOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *userOptions) apply(opts ...UserOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithUserHTTPResponse() UserOption {
	return func(o *userOptions) {
		o.isFromRPC = false
	}
}

func WithUserRPCResponse() UserOption {
	return func(o *userOptions) {
		o.isFromRPC = true
	}
}

func WithUserResponser(responser errcode.Responser) UserOption {
	return func(o *userOptions) {
		o.responser = responser
	}
}

func WithUserLogger(zapLog *zap.Logger) UserOption {
	return func(o *userOptions) {
		o.zapLog = zapLog
	}
}

func WithUserErrorToHTTPCode(e ...*errcode.Error) UserOption {
	return func(o *userOptions) {
		o.httpErrors = e
	}
}

func WithUserRPCStatusToHTTPCode(s ...*errcode.RPCStatus) UserOption {
	return func(o *userOptions) {
		o.rpcStatus = s
	}
}

func WithUserWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) UserOption {
	return func(o *userOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterUserRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic UserLogicer,
	opts ...UserOption) {

	o := &userOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &userRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type userRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                UserLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *userRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/user", r.withMiddleware("POST", "/api/v1/user", r.Create_2)...)
	r.iRouter.Handle("DELETE", "/api/v1/user/:id", r.withMiddleware("DELETE", "/api/v1/user/:id", r.DeleteByID_2)...)
	r.iRouter.Handle("PUT", "/api/v1/user/:id", r.withMiddleware("PUT", "/api/v1/user/:id", r.UpdateByID_2)...)
	r.iRouter.Handle("GET", "/api/v1/user/:id", r.withMiddleware("GET", "/api/v1/user/:id", r.GetByID_2)...)
	r.iRouter.Handle("POST", "/api/v1/user/list", r.withMiddleware("POST", "/api/v1/user/list", r.List_2)...)
	r.iRouter.Handle("POST", "/api/v1/user/delete/ids", r.withMiddleware("POST", "/api/v1/user/delete/ids", r.DeleteByIDs_2)...)
	r.iRouter.Handle("POST", "/api/v1/user/condition", r.withMiddleware("POST", "/api/v1/user/condition", r.GetByCondition_2)...)
	r.iRouter.Handle("POST", "/api/v1/user/list/ids", r.withMiddleware("POST", "/api/v1/user/list/ids", r.ListByIDs_2)...)
	r.iRouter.Handle("GET", "/api/v1/user/list", r.withMiddleware("GET", "/api/v1/user/list", r.ListByLastID_2)...)
	r.iRouter.Handle("POST", "/api/auth/login", r.withMiddleware("POST", "/api/auth/login", r.Login_0)...)
	r.iRouter.Handle("GET", "/api/user/info", r.withMiddleware("GET", "/api/user/info", r.Info_0)...)
	r.iRouter.Handle("GET", "/api/auth/codes", r.withMiddleware("GET", "/api/auth/codes", r.Codes_0)...)
	r.iRouter.Handle("POST", "/api/auth/logout", r.withMiddleware("POST", "/api/auth/logout", r.Logout_0)...)

}

func (r *userRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *userRouter) Create_2(c *gin.Context) {
	req := &CreateUserRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) DeleteByID_2(c *gin.Context) {
	req := &DeleteUserByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) UpdateByID_2(c *gin.Context) {
	req := &UpdateUserByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) GetByID_2(c *gin.Context) {
	req := &GetUserByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) List_2(c *gin.Context) {
	req := &ListUserRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) DeleteByIDs_2(c *gin.Context) {
	req := &DeleteUserByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) GetByCondition_2(c *gin.Context) {
	req := &GetUserByConditionRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByCondition(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) ListByIDs_2(c *gin.Context) {
	req := &ListUserByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) ListByLastID_2(c *gin.Context) {
	req := &ListUserByLastIDRequest{}
	var err error

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByLastID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) Login_0(c *gin.Context) {
	req := &LoginRequest{}

	var ctx context.Context = c

	out, err := r.iLogic.Login(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) Info_0(c *gin.Context) {
	req := &LoginRequest{}

	var ctx context.Context = c

	out, err := r.iLogic.Info(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) Codes_0(c *gin.Context) {
	req := &LoginRequest{}

	var ctx context.Context = c

	out, err := r.iLogic.Codes(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *userRouter) Logout_0(c *gin.Context) {
	req := &LoginRequest{}

	var ctx context.Context = c

	out, err := r.iLogic.Logout(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
