apiVersion: v1
kind: Service
metadata:
  name: school-svc
  namespace: default
spec:
  selector:
    app: school
  type: ClusterIP
  ports:
    - name: school-svc-http-port
      port: 8080
      targetPort: 8080

