apiVersion: v1
kind: Service
metadata:
  name: school-svc
  namespace: school
spec:
  selector:
    app: school
  type: NodePort
  ports:
    - name: school-svc-http-port
      port: 8080
      targetPort: 7070
      nodePort: 7070

